## Autogenerated config.py
## Documentation:
##   qute://help/configuring.html
##   qute://help/settings.html

# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

## This is here so configs done via the GUI are still loaded.
## Remove it to not load settings done via the GUI.
config.load_autoconfig()

## Aliases for commands. The keys of the given dictionary are the
## aliases, while the values are the commands they map to.
## Type: Dict
c.aliases = {'mpv': 'spawn --userscript qutebrowser_view_in_mpv.bash',
             'vlc': 'spawn --userscript qutebrowser_view_in_vlc.bash',
             'w': 'session-save',
             'q': 'close',
             'qa': 'quit',
             'wq': 'quit --save',
             'wqa': 'quit --save'}

## Always restore open sites when qutebrowser is reopened.
## Type: Bool
c.auto_save.session = True

## This setting can be used to map keys to other keys. When the key used
## as dictionary-key is pressed, the binding for the key used as
## dictionary-value is invoked instead. This is useful for global
## remappings of keys, for example to map Ctrl-[ to Escape. Note that
## when a key is bound (via `bindings.default` or `bindings.commands`),
## the mapping is ignored.
## Type: Dict
c.bindings.key_mappings = {'<Ctrl-[>': '<Escape>',
                           '<Ctrl-6>': '<Ctrl-^>',
                           '<Ctrl-M>': '<Return>',
                           '<Ctrl-J>': '<Return>',
                           '<Shift-Return>': '<Return>',
                           '<Enter>': '<Return>',
                           '<Shift-Enter>': '<Return>',
                           '<Ctrl-Enter>': '<Ctrl-Return>'}

## Allow websites to read canvas elements. Note this is needed for some
## websites to work properly.
## Type: Bool
c.content.canvas_reading = False

## Which cookies to accept.
## Type: String
## Valid values:
##   - all: Accept all cookies.
##   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
##   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
##   - never: Don't accept cookies at all.
c.content.cookies.accept = 'no-3rdparty'

## Value to send in the `Accept-Language` header. Note that the value
## read from JavaScript is always the global value.
## Type: String
c.content.headers.accept_language = 'en-US,en;q=0.5'

## Custom headers for qutebrowser HTTP requests.
## Type: Dict
c.content.headers.custom = {'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'}

## Validate SSL handshakes.
## Type: BoolAsk
## Valid values:
##   - true
##   - false
##   - ask
#c.content.ssl_strict = True

## Enable WebGL.
## Type: Bool
c.content.webgl = False

## Editor (and arguments) to use for the `open-editor` command. The
## following placeholders are defined:  * `{file}`: Filename of the file
## to be edited. * `{line}`: Line in which the caret is found in the
## text. * `{column}`: Column in which the caret is found in the text. *
## `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
## Same as `{column}`, but starting from index 0.
## Type: ShellCommand
c.editor.command = ['st', '-e', 'vim', '{file}']

## Search engines which can be used via the address bar. Maps a search
## engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
## placeholder. The placeholder will be replaced by the search term, use
## `{{` and `}}` for literal `{`/`}` signs. The search engine named
## `DEFAULT` is used when `url.auto_search` is turned on and something
## else than a URL was entered to be opened. Other search engines can be
## used by prepending the search engine name to the search term, e.g.
## `:open google qutebrowser`.
## Type: Dict
c.url.searchengines = {'DEFAULT': 'https://duckduckgo.com/?q={}',
                       'aw': 'https://wiki.archlinux.org/index.php/{}',
                       'aur': 'https://aur.archlinux.org/packages/{}',
                       'dict': 'https://www.dict.cc/?s={}',
                       'g': 'https://www.google.de/search?q={}',
                       'leo': 'https://dict.leo.org/ende?search={}',
                       'linguee': 'https://www.linguee.com/english-german/search?source=auto&query={}',
                       'wde': 'https://de.wikipedia.org/wiki/{}',
                       'wen': 'https://en.wikipedia.org/wiki/{}',
                       'y': 'https://youtube.com/results?search_query={}',
                       }

## Bindings for normal mode
config.bind('<Ctrl-M>', 'mpv')

## Load color scheme
config.source('nord-qutebrowser.py')
