" Plugins {{{
call plug#begin('~/.vim/plugged')
Plug 'vimwiki/vimwiki'
Plug 'mechatroner/rainbow_csv'
Plug 'w0rp/ale'
Plug 'wincent/command-t'
Plug 'junegunn/goyo.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'justinmk/vim-sneak'
call plug#end()
if has("autocmd")
  filetype plugin indent on
endif

" Configure vim-sneak
map f <Plug>Sneak_s
map F <Plug>Sneak_S
 " }}}

" Basics {{{
set encoding=utf-8 " Encoding
set number " Display line numbers
set splitbelow splitright " Sensible splitting behavior
set nocompatible
set nomodeline
set cursorline
" Enable autocompletion
set wildmode=longest,list,full
set wildmenu
" Change leader key
let mapleader = ','
" Set the time the leader key is active (in ms)
set timeoutlen=2000
" Show tabs
set listchars=tab:>-
" Leave insert mode
inoremap jk <ESC>
 " }}}

" Syntax highlighting {{{
let g:solarized_termcolors=256 " If using solarized color scheme
if has("syntax")
  syntax on
  colorscheme nord
endif
" }}}

" Statusline {{{
set laststatus=2
set statusline=
"set statusline+=%7*\[%n]                                  "buffernr
set statusline+=%1*\ %<%F\                                "Filename
set statusline+=%2*\ %y\                                  "FileType
set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..)
set statusline+=%5*\ %{&spelllang}\                       "Spellanguage
set statusline+=%8*\ %=\ %l:%v\                           "Rownr:Colnr
set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.
" }}}

" run programs silently {{{
command! -nargs=* RunSilent
	\ | execute ':silent !'.'<args>'
	\ | execute ':redraw!'
" }}}

" markdown preview with pandoc {{{
nmap <Leader>pc :RunSilent pandoc -f markdown -o /tmp/vim-pandoc-out.pdf % && pkill -1 mupdf<CR>
nmap <Leader>pp :RunSilent zathura /tmp/vim-pandoc-out.pdf &<CR>
 " }}}

" Search through vimwiki {{{
command! -nargs=1 Wikigrep vimgrep "<args>" $HOME/vimwiki/**/*.wiki
nnoremap <Leader>w :Wikigrep<space>
" }}}

" run make {{{
nmap <Leader>mk :RunSilent make<CR>
"}}}

" Normal, write and code modes {{{
command Normalmode set background=dark | colorscheme nord | Goyo! | set nolinebreak | set norelativenumber | set nospell | set cursorline
command Writemode set background=light | colorscheme solarized | set linebreak | set spell | set nocursorline | Goyo 80
command Codemode set background=dark | colorscheme obsidian | Goyo! | set nolinebreak | set nospell | set cursorline
nmap <Leader>nm :Normalmode<CR>
nmap <Leader>wm :Writemode<CR>
nmap <Leader>cm :Codemode<CR>
" }}}

" Insert current date {{{
nmap <Leader>d "=strftime("%Y-%m-%d")<CR>P
" }}}

" autocmds {{{
" reopening a file at same position
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
  autocmd BufRead,BufNewFile ~/.mutt/temp/mutt* :Goyo 80 | set linebreak | set spell
  " automatically deletes all trailing whitespace on save
  autocmd BufWritePre * %s/\s\+$//e
endif
" }}}

" Open vimrc {{{
nnoremap <Leader>ev :vsp ~/.vimrc<CR>
nnoremap <Leader>sv :source ~/.vimrc <bar> :doautocmd BufRead<CR>
" }}}

" Folding {{{
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=syntax
nnoremap <space> za
" }}}
