##################
#### Basics ######
##################

# Source ~/.zshrc
source ~/.zshrc

# Set path
typeset -U path
# Add ~/bin to path
# Add ruby scripts to path
path=(~/bin $(ruby -e 'print Gem.user_dir')/bin $path[@])

################
## Variables ###
################

# set EDITOR, VISUAL and PAGER variable
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"
